"""Add ProjectPlace and TravelProject models

Revision ID: a66f95ddf5f7
Revises: aac664d00c20
Create Date: 2026-02-20 18:04:21.248082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66f95ddf5f7'
down_revision: Union[str, Sequence[str], None] = 'aac664d00c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_projects_id'), 'travel_projects', ['id'], unique=False)
    op.create_index(op.f('ix_travel_projects_name'), 'travel_projects', ['name'], unique=False)
    op.create_index(op.f('ix_travel_projects_user_id'), 'travel_projects', ['user_id'], unique=False)
    op.create_table('project_places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('visited', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['travel_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'external_id', name='uq_project_places_project_id_external_id')
    )
    op.create_index(op.f('ix_project_places_external_id'), 'project_places', ['external_id'], unique=False)
    op.create_index(op.f('ix_project_places_id'), 'project_places', ['id'], unique=False)
    op.create_index(op.f('ix_project_places_project_id'), 'project_places', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_places_project_id'), table_name='project_places')
    op.drop_index(op.f('ix_project_places_id'), table_name='project_places')
    op.drop_index(op.f('ix_project_places_external_id'), table_name='project_places')
    op.drop_table('project_places')
    op.drop_index(op.f('ix_travel_projects_user_id'), table_name='travel_projects')
    op.drop_index(op.f('ix_travel_projects_name'), table_name='travel_projects')
    op.drop_index(op.f('ix_travel_projects_id'), table_name='travel_projects')
    op.drop_table('travel_projects')
    # ### end Alembic commands ###
